Feature/jwplayer adapter interpret response
jwplayer/Prebid.js pull request #30
Opened 2022-06-07 18:57 UTC by jorgeluisrocha

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Implemented the interpretResponse function for jwplayerBidAdapter.js.

2022-06-14 20:28 UTC, karimMourra requested changes

2022-06-14 20:28 UTC, karimMourra commented on test/spec/modules/jwplayerBidAdapter_spec.js
>    describe('interpretResponse for video', function() {});
missing unit tests

2022-06-28 19:53 UTC, jorgeluisrocha commented on test/spec/modules/jwplayerBidAdapter_spec.js
>    describe('interpretResponse for video', function() {});
fixed.

2022-06-30 15:32 UTC, karimMourra approved these changes
response part looks good!

2022-06-30 20:12 UTC, merged